apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-api.fullname" . }}
  labels:
    app: {{ include "employee-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "employee-api.fullname" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "employee-api.fullname" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ include "employee-api.fullname" . }}-config

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
