env:
  ENV: staging
replicaCount: 3

image:
  repository: employee-api
  tag: v1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: employee-staging.local
      paths:
        - path: /
          pathType: Prefix